import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author admin
 */
public class GIFTTREE extends javax.swing.JFrame {

    /**
     * Creates new form GIFTTREE
     */
    public GIFTTREE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmd_print = new javax.swing.JButton();
        giftbg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        paneltoPrint = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        cmd_print.setText("print your certificate");
        cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_printActionPerformed(evt);
            }
        });
        jPanel1.add(cmd_print);
        cmd_print.setBounds(720, 100, 131, 23);

        giftbg.setBackground(new java.awt.Color(255, 255, 255));
        giftbg.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(giftbg);
        giftbg.setBounds(550, 330, 830, 400);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" 1", "rtber", "bsret"},
                {"2", "sretbser", "sbe"},
                {"3", "srebytse", "hr67r6d"}
            },
            new String [] {
                "rno", "name", "class"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(750, 130, 510, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\volunteer images\\east-coast-road-beaches-kovalam-beach.jpg")); // NOI18N

        javax.swing.GroupLayout paneltoPrintLayout = new javax.swing.GroupLayout(paneltoPrint);
        paneltoPrint.setLayout(paneltoPrintLayout);
        paneltoPrintLayout.setHorizontalGroup(
            paneltoPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltoPrintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        paneltoPrintLayout.setVerticalGroup(
            paneltoPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltoPrintLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel1.add(paneltoPrint);
        paneltoPrint.setBounds(220, 70, 470, 390);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(960, 70, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_printActionPerformed
  
            printRecord(paneltoPrint);
 
    }//GEN-LAST:event_cmd_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIFTTREE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIFTTREE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIFTTREE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIFTTREE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GIFTTREE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_print;
    private javax.swing.JLabel giftbg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel paneltoPrint;
    // End of variables declaration//GEN-END:variables


     private void printRecord(JPanel panel){
         //set printer job name
         PrinterJob printerJob = PrinterJob.getPrinterJob();
         //Set Printable
         printerJob.setJobName("Print Record");
         //set Printable
         printerJob.setPrintable((Graphics graphics, PageFormat pageFormat, int pageIndex) -> {
             //check if no printable content
             if(pageIndex > 0){
                 return Printable.NO_SUCH_PAGE;
             }
             //make 2d graphics to map contents
             Graphics2D graphics2D = (Graphics2D)graphics;
             //set graphics translations
             graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
             //this is a page scale.default dhould be 0.3 i am using 0.5
             graphics2D.scale(0.5,0.5);
             
             //now paint panel as graphics2d
             panel.paint(graphics2D);
             //return if page exists
             return Printable.PAGE_EXISTS;
         });
         boolean returningResult = printerJob.printDialog();
         if(returningResult){
             try{
                 printerJob.print();
                }
         catch(PrinterException printerException){
                 JOptionPane.showMessageDialog(this,"Print Error:"+ printerException.getMessage());
                 }
        }

    }}
