import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class volunteer extends javax.swing.JFrame {
            Connection con=null;
            Statement stmt=null;
            PreparedStatement pst=null;
            ResultSet rs=null;
    public volunteer() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jtfevent = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaaddress = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtiming = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        jtype = new javax.swing.JTextField();
        jdate = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jbtpalli = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jbtadyar = new javax.swing.JButton();
        jbtkosas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jbtkovalam = new javax.swing.JButton();
        jbtthiru = new javax.swing.JButton();
        jbtneela = new javax.swing.JButton();
        jbtchennai = new javax.swing.JButton();
        jbtelliots = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jbtmarina = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(102, 0, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("HOME");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 30, 110, 60);

        jButton2.setBackground(new java.awt.Color(102, 0, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ABOUT US");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 40, 160, 39);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/icons8-close-window-32.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });
        jPanel1.add(jLabel18);
        jLabel18.setBounds(1240, 10, 32, 30);

        jButton3.setBackground(new java.awt.Color(102, 0, 204));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("KNOW YOUR CITY");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton3);
        jButton3.setBounds(850, 30, 240, 60);

        jButton5.setBackground(new java.awt.Color(102, 0, 204));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("VOLUNTEER");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton5);
        jButton5.setBounds(630, 40, 170, 40);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Place you want to Volunteer:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));
        jPanel4.add(jtfevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose a category of event", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 0, 12))); // NOI18N
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("CLEANING OF AREA");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("BIRD WATCHING");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("PLANTING TREES ");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("DISTRIBUTE SAPLINGS");
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 340, 100));

        jLabel14.setText("Event Address:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jtaaddress.setColumns(20);
        jtaaddress.setRows(5);
        jScrollPane1.setViewportView(jtaaddress);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 200, 80));

        jLabel15.setText("Event Date:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel16.setText("Event Timing:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));
        jPanel4.add(jtiming, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 110, -1));

        register.setBackground(new java.awt.Color(255, 255, 255));
        register.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        register.setForeground(new java.awt.Color(0, 102, 0));
        register.setText("REGISTER");
        register.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 1, true));
        register.setContentAreaFilled(false);
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel4.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 120, 40));
        jPanel4.add(jtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 140, 30));
        jPanel4.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 90, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 0, 12))); // NOI18N

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("2021-11-26");
        jRadioButton5.setOpaque(false);
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton5MousePressed(evt);
            }
        });

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("2021-11-30");
        jRadioButton6.setOpaque(false);
        jRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton6MousePressed(evt);
            }
        });

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("2021-11-28");
        jRadioButton7.setOpaque(false);
        jRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton6))
                    .addComponent(jRadioButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 210, -1));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(810, 180, 430, 520);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EVENTS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 160, 31);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("_________________________________________________________________________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 1206, 14);

        jTabbedPane1.setForeground(new java.awt.Color(0, 153, 0));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jbtpalli.setBackground(java.awt.SystemColor.controlLtHighlight);
        jbtpalli.setForeground(new java.awt.Color(255, 255, 255));
        jbtpalli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volunteer images/save pallikaranai.jpg"))); // NOI18N
        jbtpalli.setPreferredSize(new java.awt.Dimension(150, 150));
        jbtpalli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtpalliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jbtpalli, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jbtpalli, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MARSHLANDS OF CHENNAI", jPanel2);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtadyar.setBackground(java.awt.SystemColor.controlLtHighlight);
        jbtadyar.setForeground(new java.awt.Color(255, 255, 255));
        jbtadyar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volunteer images/adyar-river.jpg"))); // NOI18N
        jbtadyar.setPreferredSize(new java.awt.Dimension(150, 150));
        jbtadyar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtadyarActionPerformed(evt);
            }
        });
        jPanel5.add(jbtadyar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 630, 200));

        jbtkosas.setBackground(java.awt.SystemColor.controlLtHighlight);
        jbtkosas.setForeground(new java.awt.Color(255, 255, 255));
        jbtkosas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volunteer images/koasthalaiyur River.jpg"))); // NOI18N
        jbtkosas.setPreferredSize(new java.awt.Dimension(150, 150));
        jbtkosas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtkosasActionPerformed(evt);
            }
        });
        jPanel5.add(jbtkosas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 630, 220));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("ADYAR RIVER");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("KOSASTHALAIYAR RIVER");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        jTabbedPane1.addTab("RIVERS OF CHENNAI", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtkovalam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volunteer images/Kovalam-beach.jpg"))); // NOI18N
        jPanel6.add(jbtkovalam, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 195, 170));

        jbtthiru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volunteer images/east-coast-road-beaches-kovalam-beach.jpg"))); // NOI18N
        jPanel6.add(jbtthiru, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 195, 160));

        jbtneela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volunteer images/Neelankarai-Beach.jpg"))); // NOI18N
        jPanel6.add(jbtneela, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 193, 170));

        jbtchennai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volunteer images/CHENNAI BEACH.jpg"))); // NOI18N
        jPanel6.add(jbtchennai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 200, 170));

        jbtelliots.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volunteer images/elliots-beach.jpg"))); // NOI18N
        jPanel6.add(jbtelliots, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 200, 160));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("MARINA BEACH");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("ELLIOTS BEACH");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("THIRUVANMIYUR BEACH");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("KOVALAM BEACH");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("CHENNAI BEACH");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("NEELANKARAI BEACH");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        jbtmarina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volunteer images/Marina_Beach.jpg"))); // NOI18N
        jbtmarina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtmarinaActionPerformed(evt);
            }
        });
        jPanel6.add(jbtmarina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 160));

        jTabbedPane1.addTab("BEACHES OF CHENNAI", jPanel6);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "EVENT", "EVENT_TYPE", "EVENT_ADDRESS", "EVENT_TIMING", "EVENT_DATE"
            }
        ));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable1);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("SHOW");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jButton7)
                .addContainerGap(328, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(141, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(142, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(138, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("MY ACTIVITIES", jPanel3);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 180, 740, 520);

        jLabel1.setBackground(new java.awt.Color(102, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netbeans bg/forest_trees_aerial_view_145888_1280x720.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);
        jPanel1.add(jOptionPane1);
        jOptionPane1.setBounds(760, 370, 150, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtpalliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtpalliActionPerformed
        // TODO add your handling code here:
       jtfevent.setText(""+"Pallikaranai");
        jtaaddress.setText("TATA Consultance servies,SH109,Pallikaranai,Chennai,Tamilnadu");
        jRadioButton2.setEnabled(false);
        jtiming.setText(""+"9am to 12pm");
    }//GEN-LAST:event_jbtpalliActionPerformed

    private void jbtadyarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtadyarActionPerformed
     jtfevent.setText("adyar river");
        jtaaddress.setText("Check Dam,Kosathalaiyar River,Tamilnadu 601204");
        jRadioButton3.setEnabled(false);
        jtiming.setText(""+"9am to 11am");
    }//GEN-LAST:event_jbtadyarActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
 try{
     con=DriverManager.getConnection("jdbc:mysql://localhost: 3306/miniproject","root","");
     String insert="insert into myevent (EVENT, EVENT_TYPE, EVENT_ADDRESS, EVENT_TIMING, EVENT_DATE) values (?,?,?,?,?)";
     pst=con.prepareStatement (insert);
     pst.setString(1, jtfevent.getText());
     pst.setString(2, jtype.getText());
     pst.setString (3, jtaaddress.getText());
     pst.setString(4, jtiming.getText());
     pst.setString(5, jdate.getText());
     pst.execute();
     System.out.print(insert);
     JOptionPane.showMessageDialog(null,"Successfully Registered");
    }
catch (SQLException | HeadlessException e) {
    JOptionPane. showMessageDialog(null, e);
    }
    }//GEN-LAST:event_registerActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        jtype.setText("");
        jtype.setText("cleaning the place");
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        jtype.setText("");
        jtype.setText("planting trees");
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        jtype.setText("");        
        jtype.setText("bird watching");    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel18MousePressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    try{
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         Class.forName("com.mysql.cj.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","");
         Statement stmt=con.createStatement();
         String show="select * from myevent;";
         ResultSet rs=stmt.executeQuery(show);
         int rc=model.getRowCount();
         if(rc>0){
             for(int i=0;i<rc;i++){
                 model.removeRow(0);
             }
         }
         while(rs.next()){
             String EVENT=rs.getString("EVENT");
             String EVENT_TYPE=rs.getString("EVENT_TYPE");
             String EVENT_ADDRESS=rs.getString("EVENT_ADDRESS");
             String EVENT_TIMING=rs.getString("EVENT_TIMING");
             String EVENT_DATE=rs.getString("EVENT_DATE");
             model.addRow(new Object[]{EVENT,EVENT_TYPE,EVENT_ADDRESS,EVENT_TIMING,EVENT_DATE});
         }
        rs.close();
        stmt.close();
        con.close();
     }          
     catch(ClassNotFoundException | SQLException e){
         JOptionPane.showMessageDialog(null,e.getMessage());
     }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseClicked
        // TODO add your handling code here:
        jtype.setText("");
        jtype.setText("distribute saplings");
    }//GEN-LAST:event_jRadioButton4MouseClicked

    private void jRadioButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MousePressed
        // TODO add your handling code here:
        jdate.setText("");
        jdate.setText("2021-11-26");
    }//GEN-LAST:event_jRadioButton5MousePressed

    private void jRadioButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton7MousePressed
        // TODO add your handling code here:
        jdate.setText("");
        jdate.setText("2021-11-28");
    }//GEN-LAST:event_jRadioButton7MousePressed

    private void jRadioButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton6MousePressed
        // TODO add your handling code here:
        jdate.setText("");
        jdate.setText("2021-11-30");
    }//GEN-LAST:event_jRadioButton6MousePressed

    private void jbtkosasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtkosasActionPerformed
        // TODO add your handling code here:
        jtfevent.setText(""+"Kosathalaiyar River");
        jtaaddress.setText("Check Dam,Kosathalaiyar River,Tamilnadu 601204");
        jRadioButton3.setEnabled(false);
        jtiming.setText(""+"9am to 1pm");
    }//GEN-LAST:event_jbtkosasActionPerformed

    private void jbtmarinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtmarinaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbtmarinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(volunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(volunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(volunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(volunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new volunteer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtadyar;
    private javax.swing.JButton jbtchennai;
    private javax.swing.JButton jbtelliots;
    private javax.swing.JButton jbtkosas;
    private javax.swing.JButton jbtkovalam;
    private javax.swing.JButton jbtmarina;
    private javax.swing.JButton jbtneela;
    private javax.swing.JButton jbtpalli;
    private javax.swing.JButton jbtthiru;
    private javax.swing.JTextField jdate;
    private javax.swing.JTextArea jtaaddress;
    private javax.swing.JTextField jtfevent;
    private javax.swing.JTextField jtiming;
    private javax.swing.JTextField jtype;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
